"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Generate Fibonacci sequence in list

a = 0
b = 1
z =[]
while a < 4000000:
    c = a + b
    z.append(c)
    d = c + b
    z.append(d)
    a = c
    b = d
    if d >=4000000:
        break
    #print(z)

# Get even numbers

v = []
for x in z:
    if x % 2 == 0:
        v.append(x)
print(v)
w = sum(v)
print(w)
